# Generated by Django 6.0 on 2026-01-11 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.author')),
                ('category_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.category')),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='subscribers',
            field=models.ManyToManyField(through='news.AuthorCategory', to='news.category'),
        ),
    ]
