# Generated by Django 6.0 on 2026-01-11 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_authorcategory_author_subscribers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AuthorCategory',
            new_name='CategoryAuthor',
        ),
        migrations.RemoveField(
            model_name='author',
            name='subscribers',
        ),
        migrations.AddField(
            model_name='category',
            name='subscribers',
            field=models.ManyToManyField(through='news.CategoryAuthor', to='news.author'),
        ),
    ]
